version: "3.8"

services:
  db-mssql:
    profiles: ["mssql"]
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Qwerty123!
    # mssql server image isn't available for arm64 architecture, so we use azure-sql instead
    # image: mcr.microsoft.com/azure-sql-edge:1.0.4
    # If you really want to use MS SQL Server, uncomment the following line
    image: mcr.microsoft.com/mssql/server:2022-RTM-CU2-ubuntu-20.04
#    restart: always
    ports:
      - "1433:1433"
#    healthcheck:
#      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Qwerty123! -Q 'SELECT 1' || exit 1" ]
#      interval: 10s
#      retries: 10
#      start_period: 10s
#      timeout: 3s     
      
  astra-dotnet6:
    profiles: ["astra"]
    build:
      context: .
      dockerfile: ./AstraLinux.Web/Dockerfile
#    args:
#      DOTNET_VERSION: "6.0"
    ports:
      - "8080:8080"
    
  zoo1:
    image: zookeeper:3.9
    profiles: ["zookeeper"]
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183
      
  zoo2:
    image: zookeeper:3.9
    profiles: ["zookeeper"]
    hostname: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183
      
  zoo3:
    image: zookeeper:3.9
    profiles: ["zookeeper"]
    hostname: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183
      
  kafka:
    image: docker.io/bitnami/kafka:3.5
    profiles: ["kafka"]
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

volumes:
  kafka_data:
    driver: local